/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdesign;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author qwerty
 */
public final class Login extends javax.swing.JFrame {

    private static BufferedImage toBufferedImage(File file) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Person p;
    String fileName;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        p = new Person();
        p.cars = new Car[2];
        showlogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Parent = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        enterprice = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        year = new javax.swing.JComboBox<String>();
        months = new javax.swing.JComboBox<String>();
        day = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        amount = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        carPanel = new javax.swing.JPanel();
        yesCar = new javax.swing.JRadioButton();
        noCar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        carData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numOfCar = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        nameCar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameBrand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Color = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Price = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        photo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        rentPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        carYear = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Parent.setBackground(new java.awt.Color(204, 204, 255));
        Parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(204, 204, 255));
        loginPanel.setMaximumSize(new java.awt.Dimension(530, 690));
        loginPanel.setMinimumSize(new java.awt.Dimension(530, 690));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterprice.setBackground(new java.awt.Color(204, 204, 255));
        enterprice.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterprice.setText("Enter Initial Amount:");
        enterprice.setBorder(null);
        enterprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterpriceFocusLost(evt);
            }
        });
        enterprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriceActionPerformed(evt);
            }
        });
        loginPanel.add(enterprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 160, 30));

        location.setBackground(new java.awt.Color(204, 204, 255));
        location.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        location.setText("Location");
        location.setBorder(null);
        location.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                locationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationFocusLost(evt);
            }
        });
        loginPanel.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 240, 30));
        loginPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 240, 10));
        loginPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 240, -1));

        year.setBackground(new java.awt.Color(204, 204, 255));
        year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965" }));
        loginPanel.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 30));

        months.setBackground(new java.awt.Color(204, 204, 255));
        months.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        months.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April ", "May", "June", "July", "August", "September", "October", "November", "December." }));
        loginPanel.add(months, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, 30));

        day.setBackground(new java.awt.Color(204, 204, 255));
        day.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        loginPanel.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 60, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton1.setText("Next");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 250, 50));
        loginPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 60, 20));

        amount.setBackground(new java.awt.Color(204, 204, 255));
        amount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        amount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        amount.setText("1000");
        amount.setBorder(null);
        amount.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                amountCaretUpdate(evt);
            }
        });
        amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountFocusLost(evt);
            }
        });
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        loginPanel.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 70, 30));

        username.setBackground(new java.awt.Color(204, 204, 255));
        username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        username.setText("Username");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        loginPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 230, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dollar-symbol.png"))); // NOI18N
        loginPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 30, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        loginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pin.png"))); // NOI18N
        loginPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        Parent.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 680));

        carPanel.setBackground(new java.awt.Color(204, 204, 255));
        carPanel.setMaximumSize(new java.awt.Dimension(530, 690));
        carPanel.setMinimumSize(new java.awt.Dimension(530, 690));
        carPanel.setPreferredSize(new java.awt.Dimension(530, 690));
        carPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yesCar.setBackground(new java.awt.Color(204, 204, 255));
        yesCar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        yesCar.setText("Yes");
        yesCar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        yesCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesCarActionPerformed(evt);
            }
        });
        carPanel.add(yesCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 60, 30));

        noCar.setBackground(new java.awt.Color(204, 204, 255));
        noCar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        noCar.setText("No");
        noCar.setBorder(null);
        noCar.setContentAreaFilled(false);
        noCar.setVerifyInputWhenFocusTarget(false);
        noCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noCarMouseClicked(evt);
            }
        });
        carPanel.add(noCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 50, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Do You Have a car?");
        carPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 30));

        carData.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("How many cars do you have?");

        numOfCar.setBackground(new java.awt.Color(204, 204, 255));
        numOfCar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        numOfCar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numOfCar.setBorder(null);
        numOfCar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                numOfCarCaretUpdate(evt);
            }
        });
        numOfCar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                numOfCarInputMethodTextChanged(evt);
            }
        });
        numOfCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfCarActionPerformed(evt);
            }
        });

        nameCar.setBackground(new java.awt.Color(204, 204, 255));
        nameCar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameCar.setBorder(null);
        nameCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Brand:");

        nameBrand.setBackground(new java.awt.Color(204, 204, 255));
        nameBrand.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameBrand.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Price:");

        Color.setBackground(new java.awt.Color(204, 204, 255));
        Color.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Color.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Color:");

        Price.setBackground(new java.awt.Color(204, 204, 255));
        Price.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Price.setBorder(null);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton2.setText("Upload Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        rentPrice.setBackground(new java.awt.Color(204, 204, 255));
        rentPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rentPrice.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Rent Price: ");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Year:");

        carYear.setBackground(new java.awt.Color(204, 204, 255));
        carYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        carYear.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Name:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Need Cleaning:");

        jCheckBox1.setBackground(new java.awt.Color(204, 204, 255));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Need Maintenance: ");

        jCheckBox2.setBackground(new java.awt.Color(204, 204, 255));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carDataLayout = new javax.swing.GroupLayout(carData);
        carData.setLayout(carDataLayout);
        carDataLayout.setHorizontalGroup(
            carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carDataLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(carDataLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addComponent(numOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(carDataLayout.createSequentialGroup()
                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carYear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(carDataLayout.createSequentialGroup()
                                    .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(carDataLayout.createSequentialGroup()
                                            .addGap(95, 95, 95)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(carDataLayout.createSequentialGroup()
                                            .addGap(170, 170, 170)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(carDataLayout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Color, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                    .addComponent(jSeparator9)))
                                            .addGroup(carDataLayout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(1, 1, 1))
                                            .addGroup(carDataLayout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(nameCar)
                                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(carDataLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCheckBox1)))
                                    .addGap(49, 49, 49)
                                    .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(carDataLayout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCheckBox2))
                                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(carDataLayout.createSequentialGroup()
                                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel3))
                                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carDataLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(nameBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                                            .addComponent(jSeparator8)))
                                                    .addGroup(carDataLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(rentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGroup(carDataLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(179, 179, 179)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        carDataLayout.setVerticalGroup(
            carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carDataLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(carDataLayout.createSequentialGroup()
                        .addComponent(numOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(carDataLayout.createSequentialGroup()
                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(carDataLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(nameBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(carDataLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8)))
                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(carDataLayout.createSequentialGroup()
                                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(carDataLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(nameCar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(carDataLayout.createSequentialGroup()
                                        .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(3, 3, 3))
                    .addGroup(carDataLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carDataLayout.createSequentialGroup()
                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(rentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jCheckBox2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(carDataLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addComponent(carYear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(carDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(carDataLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jCheckBox1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        carPanel.add(carData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 430, 440));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton3.setText("Next");
        jButton3.setPreferredSize(new java.awt.Dimension(81, 37));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        carPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 390, 50));

        Parent.add(carPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 690));

        jPanel1.add(Parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 510, 760));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setMaximumSize(new java.awt.Dimension(1100, 690));
        jPanel2.setMinimumSize(new java.awt.Dimension(1100, 690));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 690));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loading.gif"))); // NOI18N
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 434, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterpriceFocusGained
        if (enterprice.getText().equals("Username")) {
            enterprice.setText(" ");
            enterprice.setForeground(new Color(54, 33, 89));
        }
    }//GEN-LAST:event_enterpriceFocusGained

    private void locationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationFocusGained
        if (location.getText().equals("Location")) {
            location.setText(" ");
            location.setForeground(new Color(54, 33, 89));
        }
    }//GEN-LAST:event_locationFocusGained

    private void enterpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterpriceFocusLost
        if (enterprice.getText().equals(" ")) {
            enterprice.setText("Username");
            enterprice.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_enterpriceFocusLost

    private void locationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationFocusLost
        if (location.getText().equals(" ")) {
            location.setText("Location");
            location.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_locationFocusLost

    private void amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusGained
        if (amount.getText().equals(" Amount")) {
            amount.setText(" ");
            amount.setForeground(new Color(54, 33, 89));
        }
    }//GEN-LAST:event_amountFocusGained

    private void amountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusLost
        if (amount.getText().equals(" ")) {
            amount.setText(" Amount");
            amount.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_amountFocusLost

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_amountActionPerformed

    private void nameCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            System.out.println("ping");
            photo.setIcon(null);
            JFrame j = new JFrame();
            JFileChooser choose = new JFileChooser();
            choose.showOpenDialog(null);
            File f = choose.getSelectedFile();
            fileName = f.getAbsolutePath();
            Image getAbsolutePath = null;
            String newPath = "src/uploads/CarImages/";
            File directory = new File(newPath);
            if(!directory.exists()){
                directory.mkdirs();
            }
            
            File sourceFile = null;
            File destination = null;
            String extension = fileName.substring(fileName.lastIndexOf('.')+1);
            sourceFile = new File(fileName);
            String val = newPath+nameCar.getText()+new Random().nextInt(300)+100;
            val = val.replaceAll("[^a-zA-Z0-9//]", "");  
            destination = new File(val+"."+extension);
            Files.copy(sourceFile.toPath(),destination.toPath());
            
            
            ImageIcon icon = new ImageIcon(fileName);
            Image image = icon.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            photo.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed




    private void yesCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesCarActionPerformed
        if (yesCar.isSelected()) {
            noCar.setSelected(false);
            carData.setVisible(true);
        } else {

        }
    }//GEN-LAST:event_yesCarActionPerformed

    private void numOfCarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_numOfCarInputMethodTextChanged
        
    }//GEN-LAST:event_numOfCarInputMethodTextChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame();
        if (enterprice.getText().equals("Username") || location.getText().equals("Location") || amount.getText().equals("Amount")) {
            JOptionPane.showMessageDialog(f, "All Fields are required", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                p.budget = (double) Integer.parseInt(amount.getText().trim());
                p.name = username.getText();
                p.location = location.getText();
                p.yob = (String) year.getSelectedItem() + "-" + (String) months.getSelectedItem() + "-" + (String) day.getSelectedItem();
                loginPanel.setVisible(false);
                carPanel.setVisible(true);
                carData.setVisible(false);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(f, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numOfCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfCarActionPerformed

    }//GEN-LAST:event_numOfCarActionPerformed
    int num=0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame f = new JFrame();
        
        if(noCar.isSelected()) {
            new MainFrame(p).show();
            this.setVisible(false);
            return;
        }
        
        
        if (nameCar.getText().isEmpty() || nameBrand.getText().isEmpty() || Color.getText().isEmpty() || Price.getText().isEmpty()) {
            JOptionPane.showMessageDialog(f, "All Fields are required", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(num==1){
            Car c = new Car();
            c.brand = nameBrand.getText();
            c.color = Color.getText();
            c.yob = carYear.getText();
            c.price = (double) Integer.parseInt(Price.getText().trim());
            c.name = nameCar.getText();
            c.rentPrice = (double) Integer.parseInt(rentPrice.getText().trim());
            c.image = fileName;
            p.cars[1] = c;
                    
            if(jCheckBox1.isSelected()) {
                c.needCleaning = true;
            }
            if(jCheckBox2.isSelected()) {   
                c.needMaintenance = true;
            }
            
            p.numberOfCars++;
            new MainFrame(p).show();
            this.setVisible(false);
        } 
        else if (numOfCar.getText().equalsIgnoreCase("1")) {

            Car c = new Car();
            c.yob = carYear.getText();
            c.brand = nameBrand.getText();
            c.color = Color.getText();
            c.price = (double) Integer.parseInt(Price.getText().trim());
            c.rentPrice = (double) Integer.parseInt(rentPrice.getText().trim());
            c.name = nameCar.getText();
            c.image = fileName;
            
            if(jCheckBox1.isSelected()) {   
                c.needCleaning = true;
            }
            if(jCheckBox2.isSelected()) {
                c.needMaintenance = true;
            }
            
            jCheckBox1.setSelected(false);
            jCheckBox1.setSelected(false);
            p.cars[0] = c;
            p.numberOfCars++;
            new MainFrame(p).show();
            this.setVisible(false);
                
            
        } else if (numOfCar.getText().equals("2")) {
                try{
                    numOfCar.setText("1");
                    numOfCar.setEditable(false);
                    yesCar.setEnabled(true);
                    noCar.setVisible(false);
                    num++;
                    numOfCar.setEditable(false);
                    Car c = new Car();
                    c.yob = carYear.getText();
                    c.brand = nameBrand.getText();
                    c.color = Color.getText();
                    c.price = (double) Integer.parseInt(Price.getText().trim());
                    c.rentPrice = (double) Integer.parseInt(rentPrice.getText().trim());
                    c.name = nameCar.getText();
                    c.image = fileName;
                    p.cars[0] = c;
                    p.numberOfCars++;
                            
                    if(jCheckBox1.isSelected()) {
                        c.needCleaning = true;
                    }
                    if(jCheckBox2.isSelected()) {
                        c.needMaintenance = true;
                    }
                    nameCar.setText("");
                    nameBrand.setText("");
                    Color.setText("");
                    Price.setText("");
                    rentPrice.setText("");
                    carYear.setText("");
                    jCheckBox1.setSelected(false);
                    jCheckBox1.setSelected(false);
                    photo.setIcon(null);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(f, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
                }        
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
         if (username.getText().equals("Username")) {
            username.setText(" ");
            username.setForeground(new Color(54, 33, 89));
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
         if (username.getText().equals(" ")) {
            username.setText("Username");
            username.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_usernameFocusLost

    private void enterpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriceActionPerformed

    private void noCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noCarMouseClicked
        // TODO add your handling code here:
        if(noCar.isSelected()) {
            carData.setVisible(false);
            yesCar.setSelected(false);
        }
    }//GEN-LAST:event_noCarMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void amountCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_amountCaretUpdate
        // TODO add your handling code here:
        JFrame f = new JFrame();
        Runnable doAssist = new Runnable() {
            @Override
            public void run() {
                String input = amount.getText();
                if(input.matches("[0-9]*") && !input.isEmpty()) {
                    jButton1.setEnabled(true);
                } else {
                    amount.setText("");
                }
                if(input.isEmpty()) {
                    jButton1.setEnabled(false);
                } else {
                    jButton1.setEnabled(true);
                    
                }
            }
        };
        SwingUtilities.invokeLater(doAssist);
    }//GEN-LAST:event_amountCaretUpdate

    private void numOfCarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_numOfCarCaretUpdate
        // TODO add your handling code here:
        JFrame f = new JFrame();
        Runnable doAssist = new Runnable() {
                @Override
                public void run() {
                    String input = numOfCar.getText();
                    System.out.println(input);
                    if (input.matches("[1-2]{1}") && !input.isEmpty()) {
                        jButton3.setEnabled(true);
                    } else {
                        numOfCar.setText("");
                    }
                    if(input.isEmpty()) {
                        jButton3.setEnabled(false);
                    } else {
                        jButton3.setEnabled(true);
                    }
                }
            };
            SwingUtilities.invokeLater(doAssist);
    }//GEN-LAST:event_numOfCarCaretUpdate

    public void showlogin() {
        amount.requestFocus();
        carPanel.setVisible(false);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Color;
    private javax.swing.JPanel Parent;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField amount;
    private javax.swing.JPanel carData;
    private javax.swing.JPanel carPanel;
    private javax.swing.JTextField carYear;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField enterprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField location;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JComboBox<String> months;
    private javax.swing.JTextField nameBrand;
    private javax.swing.JTextField nameCar;
    private javax.swing.JRadioButton noCar;
    private javax.swing.JTextField numOfCar;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField rentPrice;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox<String> year;
    private javax.swing.JRadioButton yesCar;
    // End of variables declaration//GEN-END:variables
}
